### ISSUE TITLE
Java Error on loading jar

### ISSUE THREAD

**Issue by Tsoccerguy3** [gamma-02/Jurassic-World-Reborn#1]
[debug.log](https://github.com/gamma-02/Jurassic-World-Reborn/files/11279096/debug.log)
[latest.log](https://github.com/gamma-02/Jurassic-World-Reborn/files/11279097/latest.log)
testing compile and run

**Comment by Tsoccerguy3** [comment]
Duplicate registration gypsum_bricks
	at net.minecraftforge.registries.DeferredRegister.register(DeferredRegister.java:220) ~[forge-1.18.2-40.2.1-universal.jar%2359!/:?]
	at net.gamma02.jurassicworldreborn.common.blocks.ModBlocks.<clinit>(ModBlocks.java:106) ~

**Comment by gamma-02** [comment]
why

just 

why are you building it??? the port isn't even in alpha?????
